services:
  - type: web
    name: openclaw
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "18789"

      - key: NODE_OPTIONS
        value: --max-old-space-size=512

      - key: SETUP_PASSWORD
        sync: false

      - key: OPENCLAW_STATE_DIR
        value: /tmp/openclaw/.openclaw

      - key: OPENCLAW_WORKSPACE_DIR
        value: /tmp/openclaw/workspace

      - key: OPENCLAW_GATEWAY_TOKEN
        generateValue: true
